package indy.pseudokod.lexer;

public enum TokenType {
    Number,
    Character,
    Text,
    Range,
    Identifier,
    Assignment,
    InRange,
    OpenParenthesis,
    CloseParenthesis,
    OpenBracket,
    CloseBracket,
    OpenBrace,
    CloseBrace,
    BinaryOperator,
    DivOperator,
    ModulusOperator,
    ComparisonOperator,
    LogicalOperator,
    DataToken,
    DataType,
    Indent,
    NewLine,
    Colon,
    Semicolon,
    Comma,
    Dot,
    Quote,
    Apostrophe,
    PrintFunction,
    GetFunction,
    IfStatement,
    ElseStatement,
    Null,
    EndOfFile
}
