package indy.pseudokod.lexer;

public enum TokenType {
    Number,
    Character,
    Text,
    Range,
    Identifier,
    Assignment,
    InRange,
    OpenParenthesis,
    CloseParenthesis,
    OpenBracket,
    CloseBracket,
    BinaryOperator,
    DivOperator,
    ModulusOperator,
    DataToken,
    DataType,
    Equal,
    NotEqual,
    LessThan,
    LessOrEqual,
    GreaterThan,
    GreaterOrEqual,
    OrOperator,
    AndOperator,
    NotOperator,
    Tabulator,
    NewLine,
    Colon,
    Semicolon,
    Comma,
    Quote,
    Apostrophe,
    Null,
    EndOfFile
}
