package indy.pseudokod.ast;

public enum NodeType {
    BinaryExpression,
    ComparisonExpression,
    LogicalExpression,
    Identifier,
    NumericLiteral,
    CharacterLiteral,
    StringLiteral,
    BooleanLiteral,
    ArrayLiteral,
    SetLiteral,
    RangeLiteral,
    Program,
    DataDeclaration,
    FunctionDeclaration,
    VariableDeclaration,
    AssignmentExpression,
    IndexExpression,
    CallExpression,
    ContinueStatement,
    PrintFunction,
    GetFunction,
    IfStatement,
    ElseStatement,
    ForStatement,
    ReturnStatement,
    ImportStatement
}
